#!/bin/bash

# you can also type numbers like 1 2 3 4 5 6 7 8 9 10 this will work the same way
for n in {1..10}
do
    echo $n
    sleep 1
done

echo "We are outside the for loop now."

# the for loop will be written like this then for n in 1 2 3 4 5 6 7 8 9 10
