#!/bin/bash


dirs=( "/home/thehuntsman/wd/documents/code/bash_scripts" "/home/thehuntsman/wd/documents/code/kvz_jobs/kayveez_car_web_v2" "/mnt/c/codes/js/" )
msg=( "Pushing files for bash scripting..." "Pushing files for career web job portal..." "Pushing files for java script web development..." )

for dir in ${!dirs[@]}
do
    
    echo "${msg[$dir]}" 
    cd ${dirs[$dir]} 
    echo $!
    PID=$!
    wait $PID
    echo "we are in : $(pwd)"

    git add *
    echo $!
    P14=$!
    wait $P14

    git commit -a
    echo $!
    P13=$!
    wait $P13

    git push
    echo $!
    P12=$!
    wait $P12 
done
# check is it fixed
echo "Updated all github repositories."
