#!/bin/bash


dirs=( `~/wd/'My Documents'/code/bash_scripts` `~/wd/'My Documents'/code/kvz_jobs/kayveez_car_web_v2` "/mnt/c/codes/js/" )
msg=( "Pushing files for bash scripting..." "Pushing files for career web job portal..." "Pushing files for java script web development..." )

for i in {0..2}
do
    
    echo "${msg[$i]}"
    cd "${dirs[$i]}" && pwd &
    echo $!
    PID=$!
    wait $PID

    git add *
    echo $!
    P14=$!
    wait $P14

    git commit -a
    echo $!
    P13=$!
    wait $P13

    git push
    echo $!
    P12=$!
    wait $P12 
done
# check is it fixed
echo "Updated all github repositories."
