#!/bin/bash

#bash_script git push
echo "Pushing files for bash scripting...."
cd ~/wd/documents/code/bash_scripts
git add *
git commit -a
git push

#career_portal git push
cd ../kvz_jobs/kayveeZ_car_web_v2/
echo "Pushing files for career web job portal...."
git add *
git commit -a
git push

#learning webjs git push
cd /mnt/c/codes/js/
echo "Pushing files for java script web development..."
git add *
git commit -a
git push
