#!/bin/bash

release_file=/etc/os-release

#universal update script
if grep -q "Arch" $release_file
then
    # The host is based on Arch, rum the pacman update command
    sudo pacman -Syu
fi

if grep -q "Ubuntu" $release_file || grep -q "Debian" $release_file
then
    # The host is based on Ubuntu or Debian
    # Run the apt version of the command
    sudo apt update
    sudo apt dist-upgrade
fi
